using EvolutionaryAlgorithms.Individuals;
using System.Collections.Generic;

namespace EvolutionaryAlgorithms.Operators.Xovers
{
    /// <summary>
    /// Base crossover class.
    /// Sets base property.
    /// </summary>
    public abstract class Xover : IXover
    {
        /// <summary>
        /// Gets the number of children generated by cross.
        /// </summary>
        /// <value>The children number.</value>
        public int ParentsNumber { get; protected set; }

        /// <summary>
        /// Gets the number of children generated by cross.
        /// </summary>
        /// <value>The children number.</value>
        public int ChildrenNumber { get; protected set; }

        /// <summary>
        /// Cross the specified parents generating the children.
        /// </summary>
        /// <param name="parents">The parents.</param>
        /// <returns>The offspring (children) of the parents.</returns>
        public abstract IList<IIndividual> Cross(IList<IIndividual> parents);
    }
}
